import {createHash} from 'node:crypto';
import {sanitizer} from '../security/sanitizer.js';
import type {NormalizedMessage} from '../providers/types.js';
import {contextUtilizationPercentOrUnavailable,utilizationBand,type ContextBuildResult,type ContextBuilderInput,type ContextItem,type ContextSource} from './types.js';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex'); const estimate=(s:string)=>Math.max(1,Math.ceil(Buffer.byteLength(s)/4));
const source=(role:NormalizedMessage['role'],raw:string):ContextSource=>role==='system'?{sourceClass:'application',trust:'trusted-instruction',provenance:'application instruction',digest:hash(raw)}:role==='user'?{sourceClass:'user',trust:'untrusted-data',provenance:'user transcript',digest:hash(raw)}:role==='tool'?{sourceClass:'tool-result',trust:'instruction-inert',provenance:'tool result',digest:hash(raw)}:{sourceClass:'remote-provider',trust:'instruction-inert',provenance:'provider transcript',digest:hash(raw)};
export function delimitUntrusted(content:string,s:ContextSource):string{const esc=(v:string)=>v.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]??c));return `<context source="${esc(s.sourceClass)}" trust="${esc(s.trust)}" provenance="${esc(s.provenance)}">\n${content.replace(/<\/context>/gi,'&lt;/context&gt;')}\n</context>`}
export class DeterministicContextBuilder{constructor(private readonly opts:{maxRecentTurns?:number;estimateTokens?:(s:string)=>number}={}){}build(input:ContextBuilderInput):ContextBuildResult{const now=input.now??new Date().toISOString(),all=[...input.history,{role:'user' as const,content:input.newInput}],start=Math.max(0,all.length-(this.opts.maxRecentTurns??all.length)),pins=new Set((input.pins??[]).filter(p=>p.status==='active').flatMap(p=>[p.target.itemId,p.target.transcriptIdentity]));const items:ContextItem[]=all.map((m,i)=>{const id=hash(`${input.sessionId??'transient'}:${i}:${m.role}:${m.content}`),src=source(m.role,m.content),protectedItem=m.role==='system'||pins.has(id)||pins.has(`turn-${i}`),inclusion=m.role==='system'?'protected':protectedItem?'pinned':i>=start?'verbatim':'omitted',safe=m.role==='system'?m.content:sanitizer.sanitizeOrBlock(m.content,'user-content','[redacted]'),content=m.role==='system'?safe:delimitUntrusted(safe,src);return Object.freeze({id,role:m.role,content,source:src,inclusion,protected:protectedItem,estimatedTokens:(this.opts.estimateTokens??estimate)(content),measuredBytes:Buffer.byteLength(content),measurementQuality:'estimated',omissionReason:inclusion==='omitted'?'capacity':undefined,transformations:[{kind:inclusion==='omitted'?'omitted':'selected',at:now}]}) as ContextItem});const selected=items.filter(i=>!['omitted','excluded','unavailable'].includes(i.inclusion)),cap=input.capacity??{rawLimit:null,effective:'percentage unavailable',responseReserve:'percentage unavailable',safetyMargin:'percentage unavailable',configuredMaxOutput:0,measurementQuality:'percentage unavailable'},tokens=selected.reduce((n,i)=>n+i.estimatedTokens,0),pct=contextUtilizationPercentOrUnavailable(tokens,cap.effective);return Object.freeze({messages:selected.map(i=>({role:i.role,content:i.content})),items,estimatedTokens:tokens,capacity:cap,utilization:{tokens,capacity:cap.effective,percent:pct,band:utilizationBand(pct)},omissions:items.filter(i=>!selected.includes(i)),transformations:items.flatMap(i=>i.transformations)})}}
export function contextCapacity(raw:number|null,output=0){if(raw===null||!Number.isFinite(raw)||raw<=0)return{rawLimit:raw,effective:'percentage unavailable' as const,responseReserve:'percentage unavailable' as const,safetyMargin:'percentage unavailable' as const,configuredMaxOutput:output,measurementQuality:'percentage unavailable' as const};const reserve=Math.max(output,Math.ceil(raw*.08)),safety=Math.max(2048,Math.ceil(raw*.02));return{rawLimit:raw,effective:Math.max(0,raw-reserve-safety),responseReserve:reserve,safetyMargin:safety,configuredMaxOutput:output,measurementQuality:'provider-reported' as const}}
