import { createHash, randomUUID } from 'node:crypto';

export type UsageSource = 'provider-reported' | 'locally-measured' | 'estimated' | 'fallback' | 'unknown';
export interface UsageObservation { readonly id: string; readonly sessionId: string; readonly operationId: string; readonly modelId: string; readonly inputTokens: number; readonly outputTokens: number; readonly cachedInputTokens: number; readonly calls: number; readonly source: UsageSource; readonly observedAt: string; readonly requestDigest?: string }
export interface UsageTotals { readonly inputTokens: number; readonly outputTokens: number; readonly cachedInputTokens: number; readonly calls: number; readonly observations: readonly UsageObservation[]; readonly measurement: UsageSource | 'mixed' }
export function validateUsage(value: UsageObservation): boolean { return Number.isInteger(value.inputTokens) && value.inputTokens >= 0 && Number.isInteger(value.outputTokens) && value.outputTokens >= 0 && Number.isInteger(value.cachedInputTokens) && value.cachedInputTokens >= 0 && Number.isInteger(value.calls) && value.calls >= 0 && value.cachedInputTokens <= value.inputTokens }
export function newUsageObservation(input: Omit<UsageObservation, 'id'>): UsageObservation { const value: UsageObservation = Object.freeze({ ...input, id: randomUUID() }); if (!validateUsage(value)) throw new Error('invalid usage observation'); return value }
export function reconcileUsage(observations: readonly UsageObservation[]): UsageTotals { const valid = observations.filter(validateUsage); const sources = new Set(valid.map((o) => o.source)); return Object.freeze({ inputTokens: valid.reduce((n, o) => n + o.inputTokens, 0), outputTokens: valid.reduce((n, o) => n + o.outputTokens, 0), cachedInputTokens: valid.reduce((n, o) => n + o.cachedInputTokens, 0), calls: valid.reduce((n, o) => n + o.calls, 0), observations: valid, measurement: sources.size === 1 ? (valid[0]?.source ?? 'unknown') : 'mixed' }); }
export function usageDigest(observation: UsageObservation): string { return createHash('sha256').update(JSON.stringify(observation)).digest('hex') }
